### PR TITLE
Bugfix cleanup task

### PR DESCRIPTION
**Pull request by tristanbettany**
Client:	Geronimo Inns 1/GERONIMO
Job:	1/00037141 Geronimo - Ongoing Support
Phase:	005 February
Stage:	[96058] CMS instagram 

As far as I can tell instagram has changed the way it responds when images are not found. This fixes that

### CODE REVIEW

**Comment by phil-lavin** [comment]
What's an example of a URL that meets the "not found" criteria?

**Comment by tristanbettany** [comment]
@phil-lavin http://scontent-b.cdninstagram.com/hphotos-xaf1/t51.2885-15/s150x150/e15/10945318_1528447137419921_87916417_n.jpg

**Comment by tristanbettany** [comment]
Realistically I would like to change the whole task to check the headers for image headers and fail on anything else as current catch's are not reliable enough. But im not sure we have the time for me to dedicate to that.

**Comment by phil-lavin** [comment]
Ok - that page returns status code 404. I'd use that, instead of checking the text.

**Comment by tristanbettany** [comment]
okies, 404 it is

**Comment by phil-lavin** [comment]
:+1:

**Pull request merged**
