### PR TITLE
Feature likes posted time

### PR DESCRIPTION
**Pull request by tristanbettany**
Propeller Communications - not chargeable 40012 Estella Bartlett overflow / training 

Save more data when saving images to make the package more useful.

### CODE REVIEW

**Comment by rob1256** [comment]
:+1:

**Comment by phil-lavin** [comment]
This is wrong

**Comment by tristanbettany** [comment]
lol

**Comment by tristanbettany** [comment]
This is a public repo @phil-lavin your still following it. Unfollow to stop notifications ;) Unless your telling me the code is wrong :)

**Pull request merged**
